name:                dmnmd
version:             0.1.0.1
github:              "smucclaw/complaw"
license:             BSD3
author:              "Meng Weng Wong"
maintainer:          "mwwong@smu.edu.sg"
copyright:           "2020 Singapore Management University"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            CLI to inter-convert DMN tables from Markdown format to JS, and more
category:            Code Generation

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Decision Model & Notation format conversion and code generation. Please see the README on GitHub at <https://github.com/smucclaw/complaw/dmnmd>

dependencies:
- base >= 4.7 && < 5
- haskeline
- containers
- split
- text
- regex-pcre
- hspec
- attoparsec
- hspec-attoparsec
- raw-strings-qq
- optparse-applicative
- MissingH
- hxt
# - fadno-xml
- megaparsec
- hspec-megaparsec
# Should this be avoided?
# Used for more convenient Iso for xml parsing
- lens
- hspec-golden
- pretty-simple
# For number parsing
- scientific
- parser-combinators

library:
  source-dirs: src
  ghc-options:
  # - -Wall
  - -Wno-unused-matches
  - -fwrite-ide-info # Used by stan, the static analyser
  - -hiedir=.hie     # Ditto

executables:
  dmnmd:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # - -Wall
    dependencies:
    - dmnmd
    - filepath

tests:
  dmnmd-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # - -Wall
    dependencies:
    - dmnmd
