name: Haskell CI

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: haskell/actions/setup@v2
      with:
        enable-stack: true
        stack-version: 'latest'

    - uses: actions/cache@v3
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('languages/haskell/**/package.yaml','languages/haskell/**/stack.yaml.lock') }}

    - name: Install dependencies
      run: |
        stack build --only-dependencies
      working-directory: languages/haskell

    - name: Build
      run: |
        stack build --test --bench --no-run-tests --no-run-benchmarks
      working-directory: languages/haskell

    - name: Test
      run: |
        stack test
      working-directory: languages/haskell
